// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABP-Uogw8C9WP0CAuDcqfPM3j55i1Oh9s',
    appId: '1:402698534638:web:b459172ee5a490fdf47dff',
    messagingSenderId: '402698534638',
    projectId: 'ondeovinho',
    authDomain: 'ondeovinho.firebaseapp.com',
    storageBucket: 'ondeovinho.firebasestorage.app',
    measurementId: 'G-5BE1V2R0BW',
  );
}

